### ISSUE TITLE
Missing Blocks

### ISSUE THREAD

**Issue by Purplecolors** [maruohon/litematica#154] opened 2020-04-16 09:59 UTC
So.. every time i Load a schematic into Minecraft, it's missing Log blocks.
can i get help? 
(Also sorry for the bad English..)

**Comment by vacla** [comment] 2020-04-16 10:15
Duplicate of #125

**Comment by maruohon** [comment] 2020-04-16 11:53
If you are on 1.15.2, then update to the latest version uploaded on 2020-04-09 (`litematica-fabric-1.15.2-0.0.0-dev.20200409.182607.jar`) which fixed this issue.

**Closed** 2020-04-19 15:09 UTC
Labels: duplicate
