### ISSUE TITLE
In the 1.15.2 Litematica version, 6 sided logs does not show

### ISSUE THREAD

**Issue by Jerry790790** [maruohon/litematica#136] opened 2020-04-07 13:42 UTC
the issue is mentioned above, 6 sided logs will never show in the schematic form. Please fix.

[BONUS]
there seems to be a bug with the hotkey settings

When EasyPlaceActiviation has a key bind, EasyPlace mode will lose it's functionality, even if it is toggled on.

**Comment by vacla** [comment] 2020-04-07 13:43
duplicate of #134

**Comment by maruohon** [comment] 2020-04-07 14:20
What do you mean by
> When EasyPlaceActivation has a key bind, EasyPlace mode will lose it's functionality, even if it is toggled on.

It seems to work for me. That key is used to basically enable the Easy Place functionality *while you use the vanilla use key (right click)*. So the activation key on its own does not place blocks, it's meant to allow you to use normal block placement even in the Easy Place mode, by requiring that additional key to be held while placing blocks to activate Easy Place functionality. In other words it's a "modifier key" not the actual action key.

**Comment by maruohon** [comment] 2020-04-09 15:33
I uploaded a new build (`litematica-fabric-1.15.2-0.0.0-dev.20200409.182607.jar`) which adds support for converting the old all-bark logs.

**Comment by maruohon** [comment] 2020-04-09 15:37
Closing as duplicate of #125 (and #134).

**Closed by maruohon** 2020-04-09 15:37 UTC
Labels: duplicate
