### ISSUE TITLE
Schematic export support

### ISSUE THREAD

**Issue by Qu1ert** [maruohon/litematica#229] opened 2020-09-09 10:34 UTC
Please make it possible to port litematica files to schematica, or support for baritone (fabritone) if possible

**Comment by maruohon** [comment] 2020-09-09 11:26
Duplicate of #207.

Also (via generic schematic conversion support) related to: #150, #108, #103, #56, #55, #54, #40, #20, #1.

**Closed** 2020-09-09 11:29 UTC
Labels: duplicate
