### ISSUE TITLE
Portal Crash (Closely Related to Issue #576)

### ISSUE THREAD

**Issue by ZenSkylark** [maruohon/litematica#622] opened 2022-11-23 15:56 UTC
Portal Crash (A Issue for NVIDIA Users) [nvoglv64.dll crash]

1.19.2 Fabric can cause Crash whenever you go every portal = Crash without a crash report

 
# EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fffa3772d20, pid=9056, tid=22096 <--- Graphics Card Driver

# C [nvoglv64.dll+0x633200] <--- It is something related to NVIDIA but this "Mod" is the main culprit of the crash due to the Frame Time

Note: That it is related to your Graphics Card (Updater Specifically)

So the Mod Version (Fabric to be Specific):

1. Litematica - Version 1.19.2 - 0.12.5
2. Malilib - Version 1.19.2 - 0.13.0

What is really happening to my Game:

1. Loading the Minecraft = No Crash
3. Loading the Minecraft World = No Crash
4. Loading a Dimension through a Portal = Crash

 
CPU: Ryzen 5 4600H

GPU GTX 1650

Memory: 16GB 2x8GB DDR4 (3200MHZ)

But here the things I have tried...

1. Reinstall Driver for NVIDIA (Using the Latest One) = "Failed"

5. Update the Java JDK 18 -> 19 = "Failed"

This might be a annoying issue especially for Mods (This might be the reason: Maybe those Performance Mods...)

 
Is it the NVIDIA Driver Latest Update (I'm not sure, I should wait for the Dev's Answer, "I love to hear it")

 
This happens to me, does it happen to you?

**Comment by vacla** [comment] 2022-11-23 16:17
Duplicate of #601

**Closed as completed** 2022-11-23 16:35 UTC
