### ISSUE TITLE
Can't place Schematics under -50 Y

### ISSUE THREAD

**Issue by Hrobitaillie** [maruohon/litematica#374] opened 2021-07-04 07:43 UTC
**NOTE**:
* Before reporting an issue, please make sure it has not already been fixed in a later version! Also make sure you have the latest version of **both Litematica and malilib!** There are occasionally changes that **will require** both mods to be updated at the same time, or something will break! The very latest development versions are available here: https://masa.dy.fi/mcmods/client_mods/ so you can quickly check if you have the latest builds. The versions on CurseForge are not usually the very latest builds, but important bugfixes will also be uploaded there.
* Please don't post simple questions like "How do I do X?" on this issue tracker. Such help requests should happen on Discord instead: https://discord.gg/VNVG3Wk (or if the previous link is broken: https://discord.gg/scicraft -> `#masas-mods`)
* Don't post issues for mod versions made for Minecraft snapshots on this tracker. The snapshot versions aren't "properly" supported or tested, they are provided as quick ports (when I have the time to make them) in a "might work, mostly" basis, and those issues should rather be handled on Discord as well.

**Minecraft version**
Which Minecraft version are you playing on?

**1.17**

**Mod version and malilib version**
Which **exact** mod version are you using? Include the **full** mod file name which includes the build date and time for the development versions, or you can see the mod version in the title of the Litematica main menu.
**"Latest" is not a version!!** It's ambiguous, it's a moving target, and very often the version is not *actually* even the latest available version at that time.

**litematica-fabric-1.17.0-0.0.0-dev.20210608.211719
malilib-fabric-1.17.0-0.10.0-dev.22+beta.1**

**Description of the bug**

**When placing a schematic under -64Y level, we can't see de schematic**
---

**Screenshots**

![image](https://user-images.githubusercontent.com/82157127/124377432-2d741500-dcac-11eb-97da-f008e9fbe496.png)

**Schematic don't load under -64Y**

**Comment by maruohon** [comment] 2021-07-04 11:43
Closing as duplicate of #362

**Closed by maruohon** 2021-07-04 11:43 UTC
Labels: bug, in-library

**Comment by Jedi5822** [comment] 2023-05-08 11:23
you need to have at layer all
