### ISSUE TITLE
Litematica crashes as soon as I open minecraft 1.14.4

### ISSUE THREAD

**Issue by 2002luis** [maruohon/litematica#59] opened 2019-08-14 17:16 UTC
18:12:39.501
Preparing to launch minecraft client for fabric-loader-0.4.8+build.159-1.14.4
18:12:40.103
Checking installations.
18:12:40.104
Minecraft client fabric-loader-0.4.8+build.159-1.14.4 is ready to start.
18:12:40.104
Starting!
18:12:40.457
Using default game log configuration client-1.12.xml (outputs XML)
18:12:46.238
Loading for game Minecraft 1.14.4
18:12:53.445

Exception in thread "main" java.lang.RuntimeException: Failed to resolve mods!
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:147)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:120)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: net.fabricmc.loader.discovery.ModResolutionException: Could not resolve valid mod collection (at: litematica requires {malilib @ [>=0.10.0-dev.19]})
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:185)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:504)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:145)
	... 2 more
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	... 4 more
18:12:53.445
Process crashed with exit code 1

**Comment by maruohon** [comment] 2019-08-14 17:26
You don't have malilib installed.

**Comment by 2002luis** [comment] 2019-08-14 17:45
thanks didnt know about requirements

**Comment by maruohon** [comment] 2019-08-14 17:49
How did you find Litematica, and did you download it from the CurseForge page? I'm getting quite a lot of these crash reports lately that are simply caused by not having malilib installed, or having an outdated version of it. I have the malilib requirement specified in bold red text on the Litematica CurseForge page, and malilib is also marked as a required dependency on the Litematica files on CurseForge. So I'd just like to know if there is still something else I could do to make it clearer that it's a requirement.

**Comment by 2002luis** [comment] 2019-08-17 15:30
I was actually just given a direct link to the download of the mod, it's not a mistake on your part from what I can see, in the sites it is listed you warn about malilib requirement, it's just that people probably dont read it and skip straight to the download.

**Closed** 2019-09-01 16:03 UTC
