### ISSUE TITLE
Invisible schematic

### ISSUE THREAD

**Issue by Viperbi** [maruohon/litematica#29] opened 2019-03-25 12:36 UTC
Hello,

Thank you first of all for your work on the mod.

I have a big schematics when I place it I only have a blue square that appears, I do not know how to place it on the map correctly so that it appears in transparency.

![2019-03-25_13 33 01](https://user-images.githubusercontent.com/48914192/54920173-d98df980-4f02-11e9-8462-142dbcae2602.png)
Look at the top on the right, for the schematic, a bloc is supposed to be where I am looking at... but it seems to be invisible.

Thanks for your time

**Comment by SunSerega** [comment] 2019-03-25 12:44
Upload this schematic and give other info that may be needed to reproduce your bug. Like version, position and rotation of schematic, etc.

**Comment by jysocial** [comment] 2019-03-25 12:50
First, check your layer mode. You can use M+PgUp or M+PgDown to cycle through the render modes. Personally Id recomment the "All below" setting as I find this best for building. Once youre in that mode, you can use PgUp to raise the rendered layer (note that this number represents the Y level in the world, so you will have to raise this number quite a lot).

**Comment by maruohon** [comment] 2019-03-25 13:07
The fact that the info shows up in the top right means that the schematic is there and you are looking at a schematic block. So since you see the placement outline but not the blocks, you either have the schematic rendering disabled (M + G by default) or you are in one of the layer rendering modes, like jy mentioned. The easiest way to check the latter is through the in-game config GUI, on the Render Layers tab.

**Comment by Viperbi** [comment] 2019-03-25 14:32
Ok sorry for this, M+G was the solution.

Thanks for your time and sorry about it.

**Comment by SunSerega** [comment] 2019-03-25 14:36
If issue is solved, you can close it yourself.

**Comment by maruohon** [comment] 2019-03-25 14:36
The latest 1.12 builds actually give you a warning when you load a new schematic, if you have the rendering disabled or you are in some other layer mode than All, since this seems to be a somewhat common derp among the users :) So the next 1.13.2 version will also have this, after I manage to finish the remaining things I want in the next release...

**Closed** 2019-03-25 14:42 UTC
