### ISSUE TITLE
When loading a schematic logs are not showing.

### ISSUE THREAD

**Issue by TimV3D** [maruohon/litematica#134] opened 2020-04-04 14:12 UTC
Trying to load tree schematics with litematica 1.15.2 but the logs of the trees are not showing.

![image](https://user-images.githubusercontent.com/41207044/78452158-eb63ba00-7689-11ea-8ef5-c77bc8f8fb18.png)

**Comment by vacla** [comment] 2020-04-04 14:18
this is probs 1.12.x schematic, and there it was like 61:2 for example, there is no conversion yet for from 1.12.x to 1.13.x and up

**Comment by maruohon** [comment] 2020-04-04 14:19
Where are the schematics from ie. what format are they in, and what MC version were they made in?

**Comment by TimV3D** [comment] 2020-04-04 14:20
The schematics were from www.minecraft-schematics.com and the MC version they were made in wasn't stated on the page

**Comment by maruohon** [comment] 2020-04-04 14:20
@vacla Old MCEdit/Schematica schematics are supported, there is conversion *from* that format in the 1.13.2+ versions. However 1.12 `*.litematic` schematics currently can not be loaded/converted automatically yet.

**Comment by maruohon** [comment] 2020-04-04 14:23
Did the trees have the full-bark log variants? There was an issue opened recently in https://github.com/maruohon/litematica/issues/125 regarding those. Could you link the exact schematic you downloaded, with such trees?

I think the vanilla flattening table probably didn't have those so they are missing from the current conversion code in Litematica. I am completely rewriting the conversion code anyway, so this should get fixed while doing that.

**Comment by TimV3D** [comment] 2020-04-04 14:27
I think these are the schematics I used, I didn't check them in another version so I don't know if they have the full bark logs. 
https://drive.google.com/drive/folders/1f0lqhFwSgj89mrUXDnKiGDhrcj0JsrBl?usp=sharing

**Comment by TimV3D** [comment] 2020-04-04 16:54
@maruohon Ok so I loaded up the schematic with the schematica mod in 1.12 and only the regular logs that are facing upwards were showing in the 1.15 preview. Would making a litematica save of it and loading that in 1.15 fix it?

**Comment by Jerry790790** [comment] 2020-04-09 02:32
I think this is just a problem with the new version of logs. When I use schematica mod for 1.12, they do load 6 sided logs.

**Comment by maruohon** [comment] 2020-04-09 15:33
I uploaded a new build (`litematica-fabric-1.15.2-0.0.0-dev.20200409.182607.jar`) which adds support for converting the old all-bark logs.

**Comment by maruohon** [comment] 2020-04-09 15:38
Closing as duplicate of #125.

**Closed by maruohon** 2020-04-09 15:38 UTC
Labels: duplicate
