### ISSUE TITLE
if i have litematica installed my mc crashes when i change dimesion

### ISSUE THREAD

**Issue by iouhgfc** [maruohon/litematica#605] opened 2022-10-31 06:26 UTC
(masa: link to log removed as it contains the client token)

**Comment by Koeseb** [comment] 2022-10-31 12:33
Same here. Did some research Apparently Nvidia fucked something up. Did Nvidia Update today and now it crashes when switching Dimension

**Comment by Hellw0rker** [comment] 2022-10-31 15:11
Is it possible to fix this bug? Or wait for a new driver from nvidia ?

**Comment by maruohon** [comment] 2022-10-31 16:06
Duplicate of #601.

**Closed as completed by maruohon** 2022-10-31 16:06 UTC
Labels: duplicate
