### ISSUE TITLE
Modrinth Release?

### ISSUE THREAD

**Issue by cootshk** [maruohon/litematica#800] opened 2023-12-14 16:17 UTC
**Is your feature request related to a problem? Please describe.**
The mod is not released on Modrinth
**Describe the solution you'd like**
I can download the mod easily from 3rd party launchers and servers 
**Describe alternatives you've considered**
Downloading manually every time, instead of features like auto-update
**Additional context**
Forgematica is on Modrinth [here](https://modrinth.com/mod/forgematica)
The Modrinth app is an actually working launcher

**Comment by maruohon** [comment] 2023-12-14 17:30
Duplicate of #524.

**Closed as completed by maruohon** 2023-12-14 17:30 UTC
Labels: duplicate
