### ISSUE TITLE
Litematica not rendering properly

### ISSUE THREAD

**Issue by Madrathyl** [maruohon/litematica#406] opened 2021-08-28 19:49 UTC
Minecraft Version 1.17.1

![Fabric files](https://user-images.githubusercontent.com/85409766/131229091-9b939413-3484-4076-9963-b2c86bd5414c.PNG)
When I render in a schematic it doesn't unload all the way and won't go away even after I unload it. It also won't move the upper layer of the schematic.

To Recreate the issue be on a multiplayer vanilla server and load a schematic and try to move it.
[(https://www.youtube.com/watch?v=jFbERi8Dwxw)]

**Comment by Bluebulu998** [comment] 2021-08-29 09:12
Litematica is not compatible with lithium

**Comment by maruohon** [comment] 2021-08-29 11:02
Duplicate of #400. The latest builds fixed that incompatibility. Here is the link to a fixed build for now, before I upload the next builds to CurseForge: https://masa.dy.fi/mcmods/litematica/litematica-fabric-1.17.1-0.0.0-dev.20210829.140021.jar

**Comment by Madrathyl** [comment] 2021-08-29 12:10
I already have that copy of litematica it still is acting up

**Comment by Bluebulu998** [comment] 2021-08-29 12:45
its not acting up

**Comment by Madrathyl** [comment] 2021-08-29 12:49
True ^

**Comment by maruohon** [comment] 2021-08-29 12:51
There are two separate, sort of similar issues.

The second issue is the recently introduced incompatibility with Lithium 0.7.4+, which made the schematic rendering basically almost never update at all.

The older issue (which is still not fixed in the above build), causes the parts of the schematic that are at least a certain distance away from the camera to not update properly to all changes. But in that case I think toggling off/on the rendering should update it, and also for example the render layer changes would still take effect, whereas with the Lithium incompatibility the render layer changes also didn't take effect at all. I'll try to figure out why that older issue happens next.

**Comment by Madrathyl** [comment] 2021-08-29 23:11
Yeah idk why it is not working still I have faith in you!

**Comment by maruohon** [comment] 2021-09-24 12:32
This should be fixed since the 2021-09-06 release.

**Closed by maruohon** 2021-09-24 12:32 UTC
Labels: bug, fixed-in-dev
