### ISSUE TITLE
Translucent Schematic Not Working

### ISSUE THREAD

**Issue by HappyCrafter156** [maruohon/litematica#371] opened 2021-07-02 01:26 UTC
I am in 1.17, running the newest update, and whenever I click my keybind for toggleTranslucentRendering, it doesn't do anything.

I'm assuming this is a bug, but it's really bothering me.

**Comment by ScorchedPsyche** [comment] 2021-07-02 03:17
The rendering is basically not working for 1.17 for now. See https://github.com/maruohon/litematica/issues/253#issuecomment-860090344 for more info.

**Comment by maruohon** [comment] 2021-07-04 11:47
Closing as duplicate of #368

**Closed by maruohon** 2021-07-04 11:47 UTC
